---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry-Run"
      logLevel:
        type: choice
        description: "Log-Level"
        default: debug
        options:
          - info
          - debug
          - trace
  push:
    branches:
      - master
      # branches that can be used for dry-runs
      - ci/renovate
      - ci/renovate/*
      # exclude branches created by renovate (by convention, requires respective config for renovate)
      - "!renovate/*"
      # explicitly include special branch for renovate config change PRs
      # see https://docs.renovatebot.com/config-validation/#validation-of-renovate-config-change-prs
      - "renovate/reconfigure"
  schedule:
    - cron: "0 0,2,4 * * 0"

env:
  # https://docs.renovatebot.com/troubleshooting/#log-debug-levels
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  # https://docs.renovatebot.com/self-hosted-configuration/#repositories
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  # https://docs.renovatebot.com/self-hosted-configuration/#username
  # If using a GitHub App as we do, the username needs to be the app name + [bot] (otherwise it fails to identify existing PRs)
  # see https://github.com/renovatebot/renovate/discussions/13708#discussioncomment-2013249
  RENOVATE_USERNAME: we-renovate[bot] # ${{ github.repository_owner }}
  # https://docs.renovatebot.com/configuration-options/#platformcommit
  RENOVATE_PLATFORM_COMMIT: "true"
  # https://docs.renovatebot.com/self-hosted-configuration/#dryrun
  # Run renovate in dry-run mode if executed in branches other than master - prevents versions in PRs/branches from being updated
  RENOVATE_DRY_RUN: "${{ inputs.dryRun || ( github.head_ref || github.ref_name ) != 'master' || false }}"
  # Renovate Automerge
  # RENOVATE_AUTOMERGE_TYPE: "branch"
  # RENOVATE_AUTOMERGE: "true"
  # Host rules
  # - Authentication to artifactory
  # - Authentication to Docker Hub - examples for Docker see https://docs.renovatebot.com/docker/#registry-authentication
  # - Host type github-tags is used to authenticate against the GitHub API for getting changelogs (among others) for private repos
  RENOVATE_HOST_RULES: '[{"matchHost":"https://artifactory.wetransform.to/","username":"${{ secrets.WETF_ARTIFACTORY_USER }}","password":"${{ secrets.WETF_ARTIFACTORY_PASSWORD }}"},{"hostType":"docker","matchHost":"docker.io","username":"${{ secrets.DOCKER_HUB_RO_USERNAME }}","password":"${{ secrets.DOCKER_HUB_RO_PASSWORD }}"},{"hostType":"github-tags","matchHost":"https://api.github.com/repos/wetransform/","token":"${{ secrets.GH_PAT_READ_WETRANSFORM }}"},{"hostType":"npm","matchHost":"npm.pkg.github.com","token":"${{ secrets.GH_PAT }}"}]'

permissions: read-all

jobs:
  renovate:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          # see https://github.com/renovatebot/renovate/blob/47c8501c412c2f53f61ca292a5039f5939c32c5d/lib/modules/platform/github/readme.md?plain=1#L28
          app-id: ${{ secrets.WE_RENOVATE_GITHUB_APP_ID }}
          private-key: "${{ secrets.WE_RENOVATE_GITHUB_PRIVATE_KEY }}"

      - name: ðŸ’¡ Self-hosted Renovate
        uses: renovatebot/github-action@5712c6a41dea6cdf32c72d92a763bd417e6606aa # v44.0.5
        with:
          token: "${{ steps.app-token.outputs.token }}"
